name = "contact"
main = "src/index.ts"
compatibility_date = "2024-11-27"

[vars]
SENDGRID_API_KEY = ""
AWARDS_COORDINATOR = ""
EMAIL_ADDRESS_AWARDS = ""
EMAIL_ADDRESS_CROSS_COUNTRY = ""
EMAIL_ADDRESS_DEBUG = ""
EMAIL_ADDRESS_EVENTS = ""
EMAIL_ADDRESS_KIT = ""
EMAIL_ADDRESS_LEAGUE = ""
EMAIL_ADDRESS_SECRETARY = ""
EMAIL_ADDRESS_WEBMASTER = ""
EMAIL_ADDRESS_WELFARE = ""