name = "cms"
main = "src/index.ts"
compatibility_date = "2022-11-27"
routes = [
  "bpj.org.uk/kit/order-successful*",
  "bpj.org.uk/leagues/cross-country*",
  "bpj.org.uk/",
  "bpj.org.uk",
  "bpj.org.uk/news*",
  "bpj.org.uk/meet-the-joggers/stuart-wild*",
  "bpj.org.uk/leagues/champions-league*",
  "bpj.org.uk/home*",
  "bpj.org.uk/leading-a-group*",
  "bpj.org.uk/charity*",
  "bpj.org.uk/social-events*",
  "bpj.org.uk/london-marathon-club-ballot*",
  "bpj.org.uk/privacy-policy*",
  "bpj.org.uk/terms-of-use*",
  "bpj.org.uk/_next*",
  "bpj.org.uk/club-constitution*",
  "bpj.org.uk/site-map*",
  "bpj.org.uk/health-and-safety-policy-and-risk-assessment*",
  "bpj.org.uk/our-races*",
  "bpj.org.uk/cms/*",
  "bpj.org.uk/claim-award*",
  "bpj.org.uk/register*",
  "bpj.org.uk/membership*",
  "bpj.org.uk/club-runs*",
  "bpj.org.uk/contact*",
  "bpj.org.uk/vacancies*",
  "bpj.org.uk/magic-mile*",
  "bpj.org.uk/race-results*",
  "bpj.org.uk/club-records*",
  "bpj.org.uk/club-standards*",
  "bpj.org.uk/couch-to-5k*",
  "bpj.org.uk/admin*",
  "bpj.org.uk/kit*",
  "bpj.org.uk/apps/*",
  "bpj.org.uk/_next/*"
]
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]
