// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:df0c48e2-a2cf-4237-8fa3-1f4298710088",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XDlTDG5YV",
    "aws_user_pools_web_client_id": "4m1gv1vnn5ckivj7r62j0dkqo0",
    "oauth": {
        "domain": "bpj-cloud.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://black-pear-joggers.netlify.com/apps/admin/",
        "redirectSignOut": "https://black-pear-joggers.netlify.com/apps/admin/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "black-pear-joggers-20190906204847-hostingbucket-cloud",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dcahkardfqybf.cloudfront.net"
};


export default awsmobile;
